TRUNCATE `books`;
insert into books (author, category, isbn, title) values ('Bjorn Pettman', 'biography', '970610157-8', 'mauris enim leo rhoncus');
insert into books (author, category, isbn, title) values ('Karleen Balme', 'science', '947072320-1', 'lorem ipsum dolor sit');
insert into books (author, category, isbn, title) values ('Jaimie Franken', 'science', '574166173-4', 'urna ut');
insert into books (author, category, isbn, title) values ('Kristos Yarrow', 'biography', '432137537-1', 'odio justo sollicitudin');
insert into books (author, category, isbn, title) values ('Harmonia Ferran', 'science', '832308014-3', 'mattis pulvinar nulla pede');
insert into books (author, category, isbn, title) values ('Riki Dimmock', 'biography', '123706502-X', 'vel augue vestibulum');
insert into books (author, category, isbn, title) values ('Leonanie Ash', 'science', '707826086-4', 'tortor quis turpis sed ante');
insert into books (author, category, isbn, title) values ('Mechelle Crutch', 'comic', '957073691-7', 'hac habitasse platea');
insert into books (author, category, isbn, title) values ('Graeme Petrusch', 'biography', '877545950-7', 'a ipsum');
insert into books (author, category, isbn, title) values ('Riobard Casero', 'comic', '290691837-7', 'a feugiat et eros vestibulum');
insert into books (author, category, isbn, title) values ('Berta Leonardi', 'science', '557209975-9', 'sed ante vivamus tortor duis');
insert into books (author, category, isbn, title) values ('Mord Treharne', 'history', '842780597-7', 'ultrices mattis');
insert into books (author, category, isbn, title) values ('Garik Garrett', 'biography', '851685874-X', 'a suscipit nulla elit');
insert into books (author, category, isbn, title) values ('Lil Jindacek', 'comic', '816579489-2', 'lacus morbi');
insert into books (author, category, isbn, title) values ('Towney Drakes', 'comic', '941259251-5', 'fusce posuere felis sed lacus');
insert into books (author, category, isbn, title) values ('Shanon Langridge', 'science', '319772483-6', 'mauris ullamcorper purus sit amet');
insert into books (author, category, isbn, title) values ('Robbyn Kendle', 'comic', '895428405-1', 'in ante vestibulum ante ipsum');
insert into books (author, category, isbn, title) values ('Amery De Andreis', 'science', '367680958-0', 'rutrum nulla nunc');
insert into books (author, category, isbn, title) values ('Andrea Martinelli', 'science', '023272203-X', 'lectus in quam fringilla');
insert into books (author, category, isbn, title) values ('Daloris Forsyde', 'biography', '357789666-3', 'aliquam convallis nunc proin');
insert into books (author, category, isbn, title) values ('Roseanne Vasovic', 'science', '989778751-8', 'amet eros');
insert into books (author, category, isbn, title) values ('Nana Castiello', 'history', '119512033-8', 'ut mauris eget massa');
insert into books (author, category, isbn, title) values ('Codi McAless', 'science', '951378311-1', 'nulla dapibus dolor vel');
insert into books (author, category, isbn, title) values ('Alastair Davio', 'biography', '535267530-0', 'nunc vestibulum ante ipsum primis');
insert into books (author, category, isbn, title) values ('Sande Fanton', 'science', '603512693-6', 'eleifend quam');
insert into books (author, category, isbn, title) values ('Viviana Roussell', 'history', '454647715-5', 'potenti in eleifend quam');
insert into books (author, category, isbn, title) values ('Brnaby Grocock', 'comic', '419857969-5', 'dolor quis odio');
insert into books (author, category, isbn, title) values ('Kristopher Gabby', 'history', '362500709-6', 'ut odio cras');
insert into books (author, category, isbn, title) values ('Cherlyn McLanaghan', 'history', '122851075-X', 'dui nec');
insert into books (author, category, isbn, title) values ('Giordano Indruch', 'comic', '695261714-0', 'lorem vitae');
insert into books (author, category, isbn, title) values ('Mozelle Kix', 'science', '713805336-3', 'convallis tortor risus dapibus');
insert into books (author, category, isbn, title) values ('Pamella Barlee', 'science', '712092786-8', 'quisque erat');
insert into books (author, category, isbn, title) values ('Alyda Nertney', 'science', '824018854-0', 'eget massa tempor convallis nulla');
insert into books (author, category, isbn, title) values ('Teador Kiernan', 'biography', '188827935-4', 'duis aliquam convallis nunc');
insert into books (author, category, isbn, title) values ('Brand Cleminshaw', 'science', '090035715-0', 'ultrices phasellus id sapien');
insert into books (author, category, isbn, title) values ('Wit Maymand', 'science', '452215826-2', 'quisque ut erat curabitur gravida');
insert into books (author, category, isbn, title) values ('Winthrop Harme', 'history', '169790894-2', 'euismod scelerisque quam turpis adipiscing');
insert into books (author, category, isbn, title) values ('Editha Weitzel', 'history', '954225128-9', 'nulla ultrices aliquet maecenas leo');
insert into books (author, category, isbn, title) values ('Milissent Vanyarkin', 'science', '610988740-4', 'eget eros elementum pellentesque quisque');
insert into books (author, category, isbn, title) values ('Crin Hannaford', 'history', '351637000-9', 'sapien sapien non');
insert into books (author, category, isbn, title) values ('Herschel Labden', 'comic', '305168083-4', 'faucibus orci luctus et ultrices');
insert into books (author, category, isbn, title) values ('Walden Schiefersten', 'comic', '478174488-5', 'mattis odio donec vitae nisi');
insert into books (author, category, isbn, title) values ('Aluino Crepin', 'history', '049374818-0', 'at lorem');
insert into books (author, category, isbn, title) values ('Magdalene Earles', 'biography', '227923898-5', 'interdum mauris non ligula pellentesque');
insert into books (author, category, isbn, title) values ('Brooke Suart', 'comic', '607731527-3', 'odio in');
insert into books (author, category, isbn, title) values ('Gonzales Haensel', 'comic', '828439795-1', 'vel nisl duis ac');
insert into books (author, category, isbn, title) values ('Dasya Brissenden', 'comic', '450239909-4', 'eleifend donec ut dolor morbi');
insert into books (author, category, isbn, title) values ('Dillon Darrigoe', 'history', '751203839-9', 'sociis natoque penatibus');
insert into books (author, category, isbn, title) values ('Roddy Gartery', 'comic', '216818145-4', 'ut massa');
insert into books (author, category, isbn, title) values ('Fidel Grayston', 'science', '118921171-8', 'quis orci eget orci vehicula');
insert into books (author, category, isbn, title) values ('Lammond Gymblett', 'history', '857582255-1', 'orci eget orci vehicula');
insert into books (author, category, isbn, title) values ('Nichole Gaine of England', 'biography', '303098148-7', 'et ultrices posuere');
insert into books (author, category, isbn, title) values ('Feliza Lages', 'comic', '212751119-0', 'libero ut massa volutpat convallis');
insert into books (author, category, isbn, title) values ('Jourdan Baud', 'comic', '452494390-0', 'molestie nibh');
insert into books (author, category, isbn, title) values ('Ed Kintish', 'biography', '539463131-X', 'in felis eu sapien');
insert into books (author, category, isbn, title) values ('Hayden MacDermid', 'history', '151030867-9', 'lorem ipsum dolor sit');
insert into books (author, category, isbn, title) values ('Nicolina Howerd', 'biography', '901517304-4', 'dictumst morbi vestibulum velit');
insert into books (author, category, isbn, title) values ('Alisander Razoux', 'science', '443571770-0', 'et ultrices');
insert into books (author, category, isbn, title) values ('Rafa Kolinsky', 'biography', '003264141-9', 'nulla eget eros elementum pellentesque');
insert into books (author, category, isbn, title) values ('Odie Spenton', 'biography', '646928984-3', 'sem fusce');
insert into books (author, category, isbn, title) values ('Goober Antonioni', 'science', '883792240-X', 'tellus semper interdum mauris ullamcorper');
insert into books (author, category, isbn, title) values ('Tessy Cudmore', 'science', '246136620-9', 'donec vitae nisi');
insert into books (author, category, isbn, title) values ('Kellby Skoggins', 'biography', '137576533-7', 'consectetuer eget rutrum');
insert into books (author, category, isbn, title) values ('Yule Petett', 'science', '503442672-2', 'eget eros elementum');
insert into books (author, category, isbn, title) values ('Abbott Lewins', 'comic', '181993924-3', 'sed ante vivamus');
insert into books (author, category, isbn, title) values ('Brande Pinnigar', 'comic', '852289855-3', 'vel lectus');
insert into books (author, category, isbn, title) values ('Thurston Druhan', 'science', '044586362-5', 'platea dictumst maecenas ut massa');
insert into books (author, category, isbn, title) values ('Moore Godlonton', 'science', '402234827-5', 'pede malesuada');
insert into books (author, category, isbn, title) values ('Had Parmby', 'comic', '222282431-1', 'imperdiet sapien urna');
insert into books (author, category, isbn, title) values ('Kory MacPaden', 'comic', '592048192-7', 'pulvinar lobortis est phasellus');
insert into books (author, category, isbn, title) values ('Marybeth Picott', 'history', '905523484-2', 'pede morbi');
insert into books (author, category, isbn, title) values ('Creighton Hackleton', 'science', '219178361-9', 'augue aliquam erat volutpat in');
insert into books (author, category, isbn, title) values ('Rudolfo Herity', 'comic', '542011128-4', 'faucibus orci luctus et');
insert into books (author, category, isbn, title) values ('Hattie Downham', 'biography', '612233966-0', 'lacus at velit vivamus vel');
insert into books (author, category, isbn, title) values ('Jacinta Burmaster', 'biography', '933207518-2', 'erat curabitur');
insert into books (author, category, isbn, title) values ('Cirilo Chable', 'history', '603583629-1', 'pellentesque at');
insert into books (author, category, isbn, title) values ('Cicely Wyke', 'biography', '844714292-2', 'turpis sed');
insert into books (author, category, isbn, title) values ('Shem Abeles', 'history', '503785574-8', 'congue eget');
insert into books (author, category, isbn, title) values ('Barny Melladew', 'comic', '857980556-2', 'duis at velit eu est');
insert into books (author, category, isbn, title) values ('Fredi Sulter', 'comic', '991143729-9', 'libero non mattis pulvinar');
insert into books (author, category, isbn, title) values ('Blythe Kaley', 'science', '566603701-3', 'mattis pulvinar nulla pede');
insert into books (author, category, isbn, title) values ('Wallace Iacomo', 'biography', '171055681-1', 'convallis eget eleifend luctus ultricies');
insert into books (author, category, isbn, title) values ('Paola Backshill', 'comic', '673962875-0', 'dignissim vestibulum vestibulum ante ipsum');
insert into books (author, category, isbn, title) values ('Tamiko Kummerlowe', 'biography', '906439596-9', 'nulla ultrices');
insert into books (author, category, isbn, title) values ('Dolley Yeude', 'science', '307195831-5', 'massa id');
insert into books (author, category, isbn, title) values ('Vida Dumberell', 'history', '311205516-0', 'consequat varius integer ac leo');
insert into books (author, category, isbn, title) values ('Rodrigo Greatrakes', 'biography', '339520577-0', 'orci luctus et ultrices posuere');
insert into books (author, category, isbn, title) values ('Jefferey Shedd', 'history', '385525103-7', 'libero ut massa');
insert into books (author, category, isbn, title) values ('Dilan Sarfass', 'history', '763459065-7', 'ligula in lacus curabitur');
insert into books (author, category, isbn, title) values ('Ronda Ecclestone', 'biography', '861617594-6', 'tortor duis');
insert into books (author, category, isbn, title) values ('Cyndia Daffey', 'science', '194258761-9', 'erat volutpat');
insert into books (author, category, isbn, title) values ('Liz Fewings', 'biography', '885153593-0', 'pede morbi porttitor');
insert into books (author, category, isbn, title) values ('Petronilla Jenkison', 'comic', '251057971-1', 'odio odio');
insert into books (author, category, isbn, title) values ('Addi Briar', 'biography', '932339294-4', 'primis in faucibus orci luctus');
insert into books (author, category, isbn, title) values ('Gaston Wadlow', 'history', '851076203-1', 'eget nunc donec');
insert into books (author, category, isbn, title) values ('Reed Anwell', 'science', '462092161-0', 'justo in hac habitasse');
insert into books (author, category, isbn, title) values ('Hodge Shimmings', 'science', '795880888-7', 'cubilia curae nulla dapibus');
insert into books (author, category, isbn, title) values ('Bentley Vanyushin', 'comic', '060354469-X', 'donec diam neque');
insert into books (author, category, isbn, title) values ('Antoinette Blades', 'history', '954118672-6', 'id luctus nec');
insert into books (author, category, isbn, title) values ('Zsa zsa Inchan', 'science', '593933315-X', 'rutrum neque aenean auctor gravida');
insert into books (author, category, isbn, title) values ('Janaya Ingre', 'comic', '405572496-9', 'in imperdiet');
insert into books (author, category, isbn, title) values ('Dennison Sturney', 'biography', '576095061-4', 'molestie lorem');
insert into books (author, category, isbn, title) values ('Ned Spellard', 'history', '866977759-2', 'neque duis');
insert into books (author, category, isbn, title) values ('Auroora Stuke', 'comic', '471557118-8', 'nulla eget');
insert into books (author, category, isbn, title) values ('Trace Burberow', 'science', '868290458-6', 'elementum ligula vehicula consequat morbi');
insert into books (author, category, isbn, title) values ('Ebonee Alanbrooke', 'biography', '332762768-1', 'parturient montes nascetur ridiculus');
insert into books (author, category, isbn, title) values ('Andrew Cotterel', 'science', '135194038-4', 'at velit eu est');
insert into books (author, category, isbn, title) values ('Klarika Olechnowicz', 'science', '051621065-3', 'pede morbi');
insert into books (author, category, isbn, title) values ('Cristin Conquest', 'science', '663458573-3', 'purus sit amet nulla quisque');
insert into books (author, category, isbn, title) values ('Ruthy Ibbett', 'comic', '861814505-X', 'dolor morbi vel lectus in');
insert into books (author, category, isbn, title) values ('Merrilee Pipe', 'science', '780414125-4', 'erat curabitur gravida nisi at');
insert into books (author, category, isbn, title) values ('Liam Balls', 'science', '076790570-9', 'ipsum praesent blandit');
insert into books (author, category, isbn, title) values ('Rafa Patty', 'comic', '432649593-6', 'tristique tortor eu pede');
insert into books (author, category, isbn, title) values ('Lorene Crysell', 'science', '533755707-6', 'proin eu mi nulla ac');
insert into books (author, category, isbn, title) values ('Warren Yurlov', 'science', '676399432-X', 'turpis eget elit sodales');
insert into books (author, category, isbn, title) values ('Spenser Alywin', 'biography', '286979962-4', 'nec sem');
insert into books (author, category, isbn, title) values ('Ewart Tows', 'science', '165944115-3', 'amet diam in');
insert into books (author, category, isbn, title) values ('Brook Petyankin', 'history', '440143126-X', 'ac tellus');
insert into books (author, category, isbn, title) values ('Audra Halwill', 'science', '833694175-4', 'fusce consequat');
insert into books (author, category, isbn, title) values ('Sara-ann Osmon', 'science', '412144038-2', 'ante vivamus tortor duis');
insert into books (author, category, isbn, title) values ('Chip O'' Timony', 'history', '184546947-X', 'neque vestibulum eget vulputate ut');
insert into books (author, category, isbn, title) values ('Joscelin Cornier', 'history', '908722740-X', 'donec diam neque vestibulum eget');
insert into books (author, category, isbn, title) values ('Agace Medcraft', 'biography', '766789814-6', 'odio in hac habitasse');
insert into books (author, category, isbn, title) values ('Callie Duchart', 'history', '490558442-6', 'maecenas pulvinar lobortis est');
insert into books (author, category, isbn, title) values ('Eirena Quiney', 'history', '745399127-7', 'donec dapibus duis at velit');
insert into books (author, category, isbn, title) values ('Barnabe Sheehan', 'biography', '638818171-6', 'quis lectus suspendisse potenti');
insert into books (author, category, isbn, title) values ('Carmelita Linde', 'comic', '150597619-7', 'amet nunc viverra');
insert into books (author, category, isbn, title) values ('Nickolas Killick', 'science', '275418669-7', 'platea dictumst aliquam augue');
insert into books (author, category, isbn, title) values ('Jennifer Friett', 'history', '395143552-6', 'etiam faucibus cursus urna ut');
insert into books (author, category, isbn, title) values ('Brigitte Buntin', 'science', '429709452-5', 'ligula pellentesque');
insert into books (author, category, isbn, title) values ('Tina Hamal', 'comic', '494079731-7', 'maecenas pulvinar lobortis est');
insert into books (author, category, isbn, title) values ('See Havenhand', 'history', '653959501-8', 'sed accumsan');
insert into books (author, category, isbn, title) values ('Sharyl Schutter', 'science', '240650813-7', 'non pretium');
insert into books (author, category, isbn, title) values ('Stephanie Leathers', 'history', '594290731-5', 'platea dictumst morbi');
insert into books (author, category, isbn, title) values ('Zebulen Swadon', 'science', '804574778-1', 'vitae quam suspendisse');
insert into books (author, category, isbn, title) values ('Lishe Tarzey', 'history', '533063080-0', 'fusce posuere felis sed');
insert into books (author, category, isbn, title) values ('Isidore Syers', 'comic', '459694387-7', 'non mattis pulvinar nulla pede');
insert into books (author, category, isbn, title) values ('Gerrie Atcherley', 'history', '536659574-6', 'metus arcu adipiscing molestie');
insert into books (author, category, isbn, title) values ('Jayme Tallis', 'science', '142650316-4', 'dolor quis odio consequat');
insert into books (author, category, isbn, title) values ('Mannie Meaddowcroft', 'science', '843556310-3', 'auctor sed');
insert into books (author, category, isbn, title) values ('Jase Granham', 'biography', '937452074-5', 'consectetuer adipiscing elit proin interdum');
insert into books (author, category, isbn, title) values ('Amery Garland', 'biography', '890704996-3', 'consequat ut nulla sed accumsan');
insert into books (author, category, isbn, title) values ('Agustin Ruston', 'biography', '503052575-0', 'sollicitudin mi');
insert into books (author, category, isbn, title) values ('Spense Amott', 'comic', '017104547-5', 'curae donec pharetra');
insert into books (author, category, isbn, title) values ('Jacinta Checci', 'comic', '784309043-6', 'mattis egestas metus aenean fermentum');
insert into books (author, category, isbn, title) values ('Bevon Casiero', 'history', '520660026-1', 'ante vel ipsum praesent');
insert into books (author, category, isbn, title) values ('Cassandra Aish', 'comic', '265360785-9', 'id massa id nisl');
insert into books (author, category, isbn, title) values ('Hubey Houlison', 'history', '192143665-4', 'duis aliquam convallis nunc proin');
insert into books (author, category, isbn, title) values ('Armstrong Depke', 'science', '326743444-0', 'pulvinar nulla pede ullamcorper augue');
insert into books (author, category, isbn, title) values ('Dominica Endacott', 'history', '234226956-0', 'penatibus et');
insert into books (author, category, isbn, title) values ('Dewain Allenby', 'biography', '434319542-2', 'lacinia aenean sit amet');
insert into books (author, category, isbn, title) values ('Amalie Toun', 'biography', '811637179-7', 'nullam orci pede');
insert into books (author, category, isbn, title) values ('Davidde Dodgson', 'history', '926461328-5', 'quam nec dui');
insert into books (author, category, isbn, title) values ('Kimberley Eck', 'biography', '059163204-7', 'ullamcorper purus sit');
insert into books (author, category, isbn, title) values ('Kiersten Houlston', 'science', '972427855-7', 'volutpat dui maecenas tristique est');
insert into books (author, category, isbn, title) values ('Leela Yearby', 'science', '495172161-9', 'at nunc commodo');
insert into books (author, category, isbn, title) values ('Pearl Jorry', 'history', '625218696-1', 'quam pharetra');
insert into books (author, category, isbn, title) values ('Verena Conaghy', 'science', '386994205-3', 'semper rutrum nulla nunc');
insert into books (author, category, isbn, title) values ('Way Gerriet', 'history', '567569405-6', 'condimentum curabitur');
insert into books (author, category, isbn, title) values ('Tamiko Gaythorpe', 'comic', '231430686-4', 'nulla sed vel enim');
insert into books (author, category, isbn, title) values ('Sullivan Hele', 'history', '710775982-5', 'et ultrices posuere cubilia');
insert into books (author, category, isbn, title) values ('Trixi Deverale', 'comic', '325468294-7', 'diam erat fermentum justo');
insert into books (author, category, isbn, title) values ('Leif Maneylaws', 'science', '832373864-5', 'ligula suspendisse ornare');
insert into books (author, category, isbn, title) values ('Essie Minihan', 'biography', '369058301-2', 'vel sem sed');
insert into books (author, category, isbn, title) values ('Dougie Harrisson', 'biography', '375305747-9', 'purus sit amet nulla quisque');
insert into books (author, category, isbn, title) values ('Laughton Dand', 'comic', '800069399-2', 'tincidunt ante vel');
insert into books (author, category, isbn, title) values ('Karole Miquelet', 'biography', '404191835-9', 'magna vestibulum aliquet ultrices');
insert into books (author, category, isbn, title) values ('Nessy Eykelbosch', 'science', '696214218-8', 'eros viverra eget');
insert into books (author, category, isbn, title) values ('Ira Hawkslee', 'history', '630001131-3', 'lorem vitae');
insert into books (author, category, isbn, title) values ('Merissa Cordner', 'comic', '663169621-6', 'ridiculus mus etiam vel augue');
insert into books (author, category, isbn, title) values ('Rodrick Reeveley', 'science', '930773709-6', 'in lacus curabitur at');
insert into books (author, category, isbn, title) values ('Candis Kenealy', 'comic', '486994961-X', 'iaculis congue vivamus metus');
insert into books (author, category, isbn, title) values ('Casey Hayen', 'comic', '960398820-0', 'porttitor pede justo eu');
insert into books (author, category, isbn, title) values ('Monika Fincham', 'history', '092858270-1', 'risus dapibus augue vel');
insert into books (author, category, isbn, title) values ('Ailee Bussell', 'history', '274323669-8', 'penatibus et magnis');
insert into books (author, category, isbn, title) values ('Pam Garmon', 'comic', '593878688-6', 'orci pede');
insert into books (author, category, isbn, title) values ('Kleon Stummeyer', 'science', '189767994-7', 'ut odio cras');
insert into books (author, category, isbn, title) values ('Leigh Kem', 'history', '035513193-5', 'interdum mauris ullamcorper');
insert into books (author, category, isbn, title) values ('Delcine Borres', 'comic', '790511693-X', 'sed sagittis');
insert into books (author, category, isbn, title) values ('Janie Heining', 'comic', '619954036-0', 'egestas metus aenean');
insert into books (author, category, isbn, title) values ('Rudolph Leisman', 'comic', '251357710-8', 'ipsum ac');
insert into books (author, category, isbn, title) values ('Fredek Ionn', 'history', '667120816-6', 'imperdiet et');
insert into books (author, category, isbn, title) values ('Oliy Shakelady', 'comic', '224786949-1', 'integer ac');
insert into books (author, category, isbn, title) values ('Leone Paling', 'history', '486906441-3', 'accumsan felis ut');
insert into books (author, category, isbn, title) values ('Isidoro Lillistone', 'comic', '782529503-X', 'sed vel');
insert into books (author, category, isbn, title) values ('Cedric Fiorentino', 'biography', '563204926-4', 'quam suspendisse');
insert into books (author, category, isbn, title) values ('Christoper Peffer', 'history', '983845692-6', 'eu felis fusce posuere felis');
insert into books (author, category, isbn, title) values ('Mollie Braunlein', 'biography', '503163254-2', 'quis tortor');
insert into books (author, category, isbn, title) values ('Armstrong Flippen', 'science', '033331603-7', 'lobortis vel dapibus at');
insert into books (author, category, isbn, title) values ('Burtie Margach', 'science', '239825780-0', 'diam vitae quam');
insert into books (author, category, isbn, title) values ('Amie Abelov', 'history', '895066586-7', 'scelerisque quam turpis');
insert into books (author, category, isbn, title) values ('Prissie Mosen', 'comic', '602538144-5', 'quis orci');
insert into books (author, category, isbn, title) values ('Sylvester Minillo', 'science', '675475642-X', 'pede morbi');
insert into books (author, category, isbn, title) values ('Domenic Luety', 'biography', '585585207-5', 'elementum nullam varius');
insert into books (author, category, isbn, title) values ('Loraine Badman', 'science', '708954728-0', 'eleifend pede libero');
insert into books (author, category, isbn, title) values ('Hayley Agronski', 'science', '868313746-5', 'in eleifend');
insert into books (author, category, isbn, title) values ('Dyane Halden', 'comic', '324025377-1', 'magnis dis parturient montes');
insert into books (author, category, isbn, title) values ('Monah Fishly', 'science', '644988859-8', 'convallis nunc proin at');
insert into books (author, category, isbn, title) values ('Otho Arne', 'biography', '841857082-2', 'phasellus sit');
insert into books (author, category, isbn, title) values ('Leyla Norssister', 'biography', '092714825-0', 'ridiculus mus etiam vel augue');
